apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: statistiques-deployment
  labels:
    app: statistiques
spec:
  replicas: 1 #  tells deployment to run 1 pod matching the template
  selector:
    matchLabels:
      app: statistiques
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: statistiques
    spec:
      containers:
      - name: statistiques-container
        image: registry.gitlab.com/gitlabodix/statistiques-ms
        imagePullPolicy: Always
        ports:
        - containerPort: 8006
---
apiVersion: v1
kind: Service
metadata:
  name: statistiques-service
spec:
  selector:
    app: statistiques
  ports:
    - port: 8006
      targetPort: 8006

