apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: statistiques-ms
build:
  artifacts:
  - image: registry.gitlab.com/gitlabodix/cvtheque-statistiques-ms-prod
deploy:
  kubectl:
    manifests:
    - ks8-local.yml
