### Database ###
spring.datasource.url=jdbc:postgresql://35.209.9.87:5432/db-statistiques-ms
spring.datasource.username=postgres
spring.datasource.password=Az@zel84
spring.datasource.driver-class-name=org.postgresql.Driver

#KAFKA
spring.kafka.bootstrap-servers=35.209.9.87:9092
spring.kafka.listener.missing-topics-fatal=false
spring.kafka.consumer.group-id=group-statistiques-ms
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer